# Generated by Django 4.0.6 on 2022-07-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.EmailField(max_length=100)),
                ('brand', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
